version: "3.8"

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    networks:
      - tinysteps-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - tinysteps-network

  ai:
    build: ./ai
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tinysteps-network

  mail:
    build: ./mail
    restart: always
    ports:
      - "8081:8081"
    networks:
      - tinysteps-network

  database:
    image: mongo:latest
    container_name: TinyStepsDB
    restart: always
    ports:
      - "27017:27017"
    networks:
      - tinysteps-network

networks:
  tinysteps-network:
    driver: bridge
